/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 24
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  aux_sym_project_name_token1 = 2,
  sym_priority = 3,
  sym_description = 4,
  anon_sym_AT = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_due = 8,
  anon_sym_deadline = 9,
  sym_property_value_date = 10,
  aux_sym_subtask_token1 = 11,
  anon_sym_PLUS = 12,
  sym_blank_line = 13,
  sym_source_file = 14,
  sym__block = 15,
  sym_project = 16,
  sym_project_name = 17,
  sym_task = 18,
  sym_property = 19,
  sym_property_name = 20,
  sym_property_value = 21,
  sym_subtask = 22,
  sym_subtask_description = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_task_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [aux_sym_project_name_token1] = "project_name_token1",
  [sym_priority] = "priority",
  [sym_description] = "description",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_due] = "due",
  [anon_sym_deadline] = "deadline",
  [sym_property_value_date] = "property_value_date",
  [aux_sym_subtask_token1] = "indent",
  [anon_sym_PLUS] = "+",
  [sym_blank_line] = "blank_line",
  [sym_source_file] = "source_file",
  [sym__block] = "_block",
  [sym_project] = "project",
  [sym_project_name] = "project_name",
  [sym_task] = "task",
  [sym_property] = "property",
  [sym_property_name] = "property_name",
  [sym_property_value] = "property_value",
  [sym_subtask] = "subtask",
  [sym_subtask_description] = "subtask_description",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_task_repeat1] = "task_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_project_name_token1] = aux_sym_project_name_token1,
  [sym_priority] = sym_priority,
  [sym_description] = sym_description,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_due] = anon_sym_due,
  [anon_sym_deadline] = anon_sym_deadline,
  [sym_property_value_date] = sym_property_value_date,
  [aux_sym_subtask_token1] = aux_sym_subtask_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_blank_line] = sym_blank_line,
  [sym_source_file] = sym_source_file,
  [sym__block] = sym__block,
  [sym_project] = sym_project,
  [sym_project_name] = sym_project_name,
  [sym_task] = sym_task,
  [sym_property] = sym_property,
  [sym_property_name] = sym_property_name,
  [sym_property_value] = sym_property_value,
  [sym_subtask] = sym_subtask,
  [sym_subtask_description] = sym_subtask_description,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_task_repeat1] = aux_sym_task_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_project_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_due] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deadline] = {
    .visible = true,
    .named = false,
  },
  [sym_property_value_date] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_subtask_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_project] = {
    .visible = true,
    .named = true,
  },
  [sym_project_name] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_property_value] = {
    .visible = true,
    .named = true,
  },
  [sym_subtask] = {
    .visible = true,
    .named = true,
  },
  [sym_subtask_description] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_task_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_description = 1,
  field_name = 2,
  field_priority = 3,
  field_project_name = 4,
  field_subtask_description = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_description] = "description",
  [field_name] = "name",
  [field_priority] = "priority",
  [field_project_name] = "project_name",
  [field_subtask_description] = "subtask_description",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_project_name, 1},
  [1] =
    {field_description, 1},
    {field_priority, 0},
  [3] =
    {field_subtask_description, 2},
  [4] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '!') ADVANCE(25);
      if (lookahead == '(') ADVANCE(29);
      if (lookahead == ')') ADVANCE(30);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '@') ADVANCE(28);
      if (lookahead == 'd') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '!') ADVANCE(25);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '@') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_project_name_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_project_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_priority);
      if (lookahead == '!') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_description);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '@') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_description);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_due);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_deadline);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_property_value_date);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_subtask_token1);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_blank_line);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 20},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 20},
  [6] = {.lex_state = 20},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 20},
  [10] = {.lex_state = 20},
  [11] = {.lex_state = 20},
  [12] = {.lex_state = 20},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_priority] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_due] = ACTIONS(1),
    [anon_sym_deadline] = ACTIONS(1),
    [sym_property_value_date] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym__block] = STATE(2),
    [sym_project] = STATE(2),
    [sym_task] = STATE(2),
    [sym_subtask] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(5),
    [sym_priority] = ACTIONS(7),
    [aux_sym_subtask_token1] = ACTIONS(9),
    [sym_blank_line] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      anon_sym_EQ,
    ACTIONS(7), 1,
      sym_priority,
    ACTIONS(9), 1,
      aux_sym_subtask_token1,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_blank_line,
    STATE(3), 5,
      sym__block,
      sym_project,
      sym_task,
      sym_subtask,
      aux_sym_source_file_repeat1,
  [23] = 6,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(22), 1,
      sym_priority,
    ACTIONS(25), 1,
      aux_sym_subtask_token1,
    ACTIONS(28), 1,
      sym_blank_line,
    STATE(3), 5,
      sym__block,
      sym_project,
      sym_task,
      sym_subtask,
      aux_sym_source_file_repeat1,
  [46] = 4,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_AT,
    STATE(6), 2,
      sym_property,
      aux_sym_task_repeat1,
    ACTIONS(33), 4,
      anon_sym_EQ,
      sym_priority,
      aux_sym_subtask_token1,
      sym_blank_line,
  [63] = 4,
    ACTIONS(35), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(8), 2,
      sym_property,
      aux_sym_task_repeat1,
    ACTIONS(39), 4,
      anon_sym_EQ,
      sym_priority,
      aux_sym_subtask_token1,
      sym_blank_line,
  [80] = 4,
    ACTIONS(35), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym_property,
      aux_sym_task_repeat1,
    ACTIONS(43), 4,
      anon_sym_EQ,
      sym_priority,
      aux_sym_subtask_token1,
      sym_blank_line,
  [97] = 4,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      anon_sym_AT,
    STATE(7), 2,
      sym_property,
      aux_sym_task_repeat1,
    ACTIONS(47), 4,
      anon_sym_EQ,
      sym_priority,
      aux_sym_subtask_token1,
      sym_blank_line,
  [114] = 4,
    ACTIONS(35), 1,
      anon_sym_AT,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym_property,
      aux_sym_task_repeat1,
    ACTIONS(54), 4,
      anon_sym_EQ,
      sym_priority,
      aux_sym_subtask_token1,
      sym_blank_line,
  [131] = 2,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 5,
      anon_sym_EQ,
      sym_priority,
      anon_sym_AT,
      aux_sym_subtask_token1,
      sym_blank_line,
  [142] = 2,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 5,
      anon_sym_EQ,
      sym_priority,
      anon_sym_AT,
      aux_sym_subtask_token1,
      sym_blank_line,
  [153] = 2,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 4,
      anon_sym_EQ,
      sym_priority,
      aux_sym_subtask_token1,
      sym_blank_line,
  [163] = 2,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 4,
      anon_sym_EQ,
      sym_priority,
      aux_sym_subtask_token1,
      sym_blank_line,
  [173] = 2,
    STATE(20), 1,
      sym_property_name,
    ACTIONS(72), 2,
      anon_sym_due,
      anon_sym_deadline,
  [181] = 2,
    ACTIONS(74), 1,
      aux_sym_project_name_token1,
    STATE(12), 1,
      sym_project_name,
  [188] = 2,
    ACTIONS(76), 1,
      aux_sym_project_name_token1,
    STATE(5), 1,
      sym_subtask_description,
  [195] = 2,
    ACTIONS(78), 1,
      sym_property_value_date,
    STATE(23), 1,
      sym_property_value,
  [202] = 1,
    ACTIONS(80), 1,
      sym_description,
  [206] = 1,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
  [210] = 1,
    ACTIONS(84), 1,
      anon_sym_PLUS,
  [214] = 1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
  [218] = 1,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
  [222] = 1,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
  [226] = 1,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 63,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 97,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 131,
  [SMALL_STATE(10)] = 142,
  [SMALL_STATE(11)] = 153,
  [SMALL_STATE(12)] = 163,
  [SMALL_STATE(13)] = 173,
  [SMALL_STATE(14)] = 181,
  [SMALL_STATE(15)] = 188,
  [SMALL_STATE(16)] = 195,
  [SMALL_STATE(17)] = 202,
  [SMALL_STATE(18)] = 206,
  [SMALL_STATE(19)] = 210,
  [SMALL_STATE(20)] = 214,
  [SMALL_STATE(21)] = 218,
  [SMALL_STATE(22)] = 222,
  [SMALL_STATE(23)] = 226,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 2, 0, 2),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 2, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask, 3, 0, 3),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subtask, 3, 0, 3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 3, 0, 2),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 3, 0, 2),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask, 4, 0, 3),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subtask, 4, 0, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtask_description, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subtask_description, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 4),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 5, 0, 4),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project_name, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project_name, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project, 2, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project, 2, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [82] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_name, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_value, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dadoot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dadoot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
